CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	TITLE VARCHAR(20) NOT NULL,
	WRITER VARCHAR(20) NOT NULL,
	CONTENT VARCHAR(100) NOT NULL,
	CNT INT DEFAULT 0,
	REGDATE DATE DEFAULT SYSDATE
);

INSERT INTO BOARD(BID,TITLE,WRITER,CONTENT) VALUES(1,'제목','작성자','내용');
INSERT INTO BOARD(BID,TITLE,WRITER,CONTENT) VALUES(2,'제목1','작성자1','내용');
INSERT INTO BOARD(BID,TITLE,WRITER,CONTENT) VALUES(3,'제목2','작성자2','내용');
INSERT INTO BOARD(BID,TITLE,WRITER,CONTENT) VALUES(4,'제목3','작성자3','내용');
INSERT INTO BOARD(BID,TITLE,WRITER,CONTENT) VALUES(5,'제목4','작성자4','내용');

SELECT * FROM BOARD WHERE TITLE LIKE '%제%' ORDER BY BID DESC;

select * from member;